// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGFP.Infra.DAO.DbContexto;

namespace SGFP.Infra.Migrations
{
    [DbContext(typeof(DbContexto))]
    [Migration("20181218025321_validacao")]
    partial class validacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SGFP.Domain.Entidades.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Nota")
                        .HasColumnName("NOTA")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnName("TEXTO")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("ID");

                    b.ToTable("SGFP_001_AVALIACAO");
                });
#pragma warning restore 612, 618
        }
    }
}
