// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGFP.Infra.DAO.DbContexto;

namespace SGFP.Infra.Migrations
{
    [DbContext(typeof(DbContexto))]
    partial class DbContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SGFP.Domain.Entidades.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Nota")
                        .HasColumnName("NOTA")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnName("TEXTO")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasName("PK_001");

                    b.ToTable("SGFP_001_AVALIACAO");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Base.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo")
                        .HasColumnName("FLAG_ATIVO")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnName("CPF")
                        .HasColumnType("varchar(17)");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<Guid?>("EmailId");

                    b.Property<Guid?>("EnderecoId");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnName("PRIMEIRO_NOME")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnName("RG")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Sexo")
                        .HasColumnName("SEXO")
                        .HasColumnType("int");

                    b.Property<Guid?>("TelefoneId");

                    b.Property<string>("UltimoNome")
                        .IsRequired()
                        .HasColumnName("ULTIMO_NOME")
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("ID");

                    b.HasIndex("EmailId");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("TelefoneId");

                    b.ToTable("Pessoa");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pessoa");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Carro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AnoFabricao")
                        .HasColumnName("ANO_FABRICAO")
                        .HasColumnType("datetime");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnName("CHASSI")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnName("COR")
                        .HasColumnType("varchar(12)");

                    b.Property<Guid?>("DonoId");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnName("MARCA")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnName("MODELO")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnName("PLACA")
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("DonoId");

                    b.HasIndex("Id")
                        .HasName("PK_002");

                    b.ToTable("SGFP_002_CARRO");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EstadoId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasColumnType("varchar(35)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("Id")
                        .HasName("PK_003");

                    b.ToTable("SGFP_003_CIDADE");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("SGFP_005_DOCUMENTO");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnName("ENDERECO")
                        .HasColumnType("varchar(35)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("SENHA")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasName("PK_006");

                    b.ToTable("SGFP_006_EMAIL");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Andress")
                        .IsRequired()
                        .HasColumnName("ENDERECO")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("CEP")
                        .HasColumnName("CEP")
                        .HasColumnType("varchar(8)");

                    b.Property<Guid?>("CidadeId");

                    b.Property<string>("Complemento")
                        .HasColumnName("COMPLEMENTO")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnName("MUNICIPIO")
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("Id")
                        .HasName("PK_007");

                    b.ToTable("SGFP_007_ENDERECO");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasColumnType("varchar(15)");

                    b.Property<Guid?>("PaisId");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnName("SIGLA")
                        .HasColumnType("char(2)");

                    b.HasKey("Id")
                        .HasName("PK_008");

                    b.HasIndex("PaisId");

                    b.ToTable("SGFP_008_ESTADO");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.MaoDeObra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo")
                        .HasColumnName("FLAG_ATIVO")
                        .HasColumnType("bit");

                    b.Property<double?>("JornadaTrabalho")
                        .HasColumnName("JORNADA_TRABALHO")
                        .HasColumnType("float");

                    b.Property<double?>("LimiteHoraExtra")
                        .HasColumnName("LIMITE_HORA_EXTRA")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TipoMaoObra")
                        .IsRequired()
                        .HasColumnName("TIPO_MAO_OBRA")
                        .HasColumnType("varchar(25)");

                    b.Property<double?>("Valor")
                        .HasColumnName("VALOR")
                        .HasColumnType("float");

                    b.Property<double?>("ValorHoraExtra")
                        .HasColumnName("VALOR_HORA_EXTRA")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK_010");

                    b.ToTable("SGFP_010_MAO_DE_OBRA");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Orcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CarroId");

                    b.Property<Guid?>("ClienteId");

                    b.Property<Guid?>("DocumentoId");

                    b.Property<DateTime>("Entrada")
                        .HasColumnName("ENTRADA")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Entrega")
                        .HasColumnName("ENTREGA")
                        .HasColumnType("datetime");

                    b.Property<string>("ListaOrcamento")
                        .HasColumnName("LISTA_ORCAMENTO")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("ServicoId");

                    b.Property<int>("Status")
                        .HasColumnName("STATUS")
                        .HasColumnType("int");

                    b.Property<double>("ValorOrcamento")
                        .HasColumnName("VALOR_ORCAMENTO")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK_011");

                    b.HasIndex("CarroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("ServicoId");

                    b.ToTable("SGFP_011_ORCAMENTO");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnName("SIGLA")
                        .HasColumnType("char(3)");

                    b.HasKey("Id")
                        .HasName("PK_012");

                    b.ToTable("SGFP_012_PAIS");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasColumnName("NOME_SERVICO")
                        .HasColumnType("varchar(35)");

                    b.Property<double>("Valor")
                        .HasColumnName("VALOR")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK_013");

                    b.ToTable("SGFP_013_SERVICO");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Telefone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasColumnName("DDD")
                        .HasColumnType("char(3)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnName("NUMERO")
                        .HasColumnType("char(10)");

                    b.Property<int>("TipoTelefone")
                        .HasColumnName("TIPO_TELEFONE")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_014");

                    b.ToTable("SGFP_014_TELEFONE");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Cliente", b =>
                {
                    b.HasBaseType("SGFP.Domain.Entidades.Base.Pessoa");

                    b.Property<Guid?>("AvaliacaoId");

                    b.Property<Guid?>("CarroId");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("CarroId");

                    b.HasIndex("Id")
                        .HasName("PK_004");

                    b.ToTable("SGFP_004_CLIENTE");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Funcionario", b =>
                {
                    b.HasBaseType("SGFP.Domain.Entidades.Base.Pessoa");

                    b.Property<int>("Categoria")
                        .HasColumnName("CATEGORIA")
                        .HasColumnType("int");

                    b.HasIndex("Id")
                        .HasName("PK_009");

                    b.ToTable("SGFP_009_FUNCIONARIO");

                    b.HasDiscriminator().HasValue("Funcionario");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Base.Pessoa", b =>
                {
                    b.HasOne("SGFP.Domain.Entidades.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId");

                    b.HasOne("SGFP.Domain.Entidades.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId");

                    b.HasOne("SGFP.Domain.Entidades.Telefone", "Telefone")
                        .WithMany()
                        .HasForeignKey("TelefoneId");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Carro", b =>
                {
                    b.HasOne("SGFP.Domain.Entidades.Base.Pessoa", "Dono")
                        .WithMany()
                        .HasForeignKey("DonoId");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Cidade", b =>
                {
                    b.HasOne("SGFP.Domain.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Endereco", b =>
                {
                    b.HasOne("SGFP.Domain.Entidades.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Estado", b =>
                {
                    b.HasOne("SGFP.Domain.Entidades.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Orcamento", b =>
                {
                    b.HasOne("SGFP.Domain.Entidades.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("CarroId");

                    b.HasOne("SGFP.Domain.Entidades.Base.Pessoa", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("SGFP.Domain.Entidades.Documento", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId");

                    b.HasOne("SGFP.Domain.Entidades.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId");
                });

            modelBuilder.Entity("SGFP.Domain.Entidades.Cliente", b =>
                {
                    b.HasOne("SGFP.Domain.Entidades.Avaliacao", "Avaliacao")
                        .WithMany()
                        .HasForeignKey("AvaliacaoId");

                    b.HasOne("SGFP.Domain.Entidades.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("CarroId");
                });
#pragma warning restore 612, 618
        }
    }
}
